name: BedWars
main: xyz.acrylicstyle.bedwars.BedWars
version: 0.0.1-SNAPSHOT
api-version: 1.8.8
author: acrylic-style
depend:
  - ProtocolLib
  - TomeitoLib
  - HolographicDisplays
commands:
  forcestart:
    usage: /<command>
    description: Start the game forcefully.
    permission: bedwars.start
    aliases: [startgame]
  forcestop:
    usage: /<command>
    description: Stop the game forcefully and reset all constant settings to the default.
    permission: bedwars.stop
    aliases: [stopgame]
  setspawn:
    usage: /<command>
    description: set spawn point of the bedwars.
    permission: bedwars.setspawn
  seteventtime:
    usage: /<command>
    description: "set event time for xx faster"
    permission: bedwars.seteventtime
  toggleblockprotection:
    usage: /<command>
    description: "Toggles block protection"
    permission: bedwars.toggleblockprotection
  setrespawntime:
    usage: /<command>
    description: "Set respawn time in seconds"
    permission: bedwars.setrespawntime
  modifiers:
    usage: /<command>
    description: "Apply modifiers to the game"
    permission: bedwars.modifiers