name: BedWars
main: xyz.acrylicstyle.bedwars.BedWars
version: 0.0.1-SNAPSHOT
api-version: 1.8.8
author: acrylic-style
depend:
  - ProtocolLib
  - TomeitoLib
commands:
  forcestart:
    usage: /<command>
    description: Start the game forcefully.
    permission: bedwars.start
    aliases: [startgame]
  forcestop:
    usage: /<command>
    description: Stop the game forcefully and reset all constant settings to the default.
    permission: bedwars.stop
    aliases: [stopgame]